model: DriftDiT-B16
img_size: 256
in_channels: 3
num_classes: 1000
batch_nc: 8
batch_n_pos: 32
batch_n_neg: 32
batch_n_uncond: 32
temperatures:
  - 0.02
  - 0.05
  - 0.2
lr: 0.0002
weight_decay: 0.01
grad_clip: 2.0
ema_decay: 0.999
warmup_steps: 5000
epochs: 100
alpha_min: 1.0
alpha_max: 4.0
alpha_sampling: power
alpha_power: 5.0
use_feature_encoder: true
feature_encoder_arch: convnextv2-large
feature_encoder_path: checkpoints/encoders/convnextv2-large-22k-224
vae_path: checkpoints/vae/sd-vae-ft-mse
kernel: l2 # l2 | gaussian
kernel_normalization: xy # xy | y
queue_size: 32
uncond_queue_size: 256
label_dropout: 0.1
loader_batch_size: 256
preview_classes: 16
